### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by kolibril13** [flipdot/manim-gallery#7]
Hi, 
When I understood it the right way, this is how the workflow of contributing can be (in my case with the IDE pycharm)

0. fork the repo (if not already forked)
1. Pull changes to the local repo, so that the master branch is up to date.
2. Create a new local branch in pycharm, where I want to add a new script.
3. Create a new file, which is the new script. (In my case that means: opening my local manim-fork, copy my script, then changing back to manim-gallery-fork, pasting the script)
4. Commit the new changes in my loal repo
5. Push it to the remote github fork
6. make a pull request to the remote github origin

I think I do it to complicated. What would be the optimal solution for the workflow?

**Comment by soerface** [comment]
That's pretty much it, yeah. It is also recommended by github, see their help: https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

> (In my case that means: opening my local manim-fork, copy my script, then changing back to manim-gallery-fork, pasting the script)

This one I don't really understand, "changing back to manim-gallery-fork". On your machine, you should have two remotes: `origin`, which points to `git@github.com:kolibril13/manim-gallery.git`, and you may add a second remote `upstream`, which points to `git@github.com:flipdot/manim-gallery.git` (`git remote add <NAME> <URL>`).

Now, when you want to start working on a new feature:
```git checkout master
git pull upstream master
git push origin master
git checkout -b lissajous_curve
# work on and test the script
git add src/examples
git commit -m "Add lissajous curve example"
git push origin lissajous_curve
```
...and create a pull request. If after some discussions you want to make some changes to the pull request, just go back to PyCharm, `git pull` (a maintainer may have made changes), make your changes, commit them, and push them to your own repo with a simple `git push`. The maintainers will be notified of your changes and it can be discussed if all issues were adressed. Creating a new pull request is not necessary and confusing, since the discussion will be left in the old pull request.

I hope this helps to clear up some questions. Probably it's a bit cumbersome when getting started with git, it's just a while ago I started using it, so maybe I forgot some things I take for granted - don't hesitate to ask questions :) It is also possible to check in a [CONTRIBUTING.md file](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors), maybe I should create one in the future.

**Comment by kolibril13** [comment]
Thanks for your answer!
I will try this soon!

> This one I don't really understand, "changing back to manim-gallery-fork"

On my machine I have two repos (separate projects):
* One is the manim repo, where all the development and animating takes place
* One is the manim-gallery repo. 

When I want to contribute to the manim-gallery gallery, I have to reopen the manim project to get my files copied, and then paste them into the manim-gallery project on my machine.

I see that your workflow is super useful, when it comes to complex projects, buuuut it might be a little overkill for this kind of project, where the main idea is to add single files.

So here I have another Option:
There is a "Propose new file" option, when I am in my browser in the original repo.
For me, this would be the more streight forward approach.
I will try this just now with a make_brace.py file.

**Comment by kolibril13** [comment]
Oh wow, the "Propose new file" is super clever!
It creates a new branch in my git fork, and makes then a pull request.

It also comes to my mind that it is really not necessary for people to have the "manim-gallery" local on their computer.

**Comment by soerface** [comment]
> I have to reopen the manim project to get my files copied

Ah, I see. I've pushed manim onto pypi a while a go. Therefore, you can just use "pip install manimlib", and then use `manim file.py Scene` directly from the command line. If you have installed all the depencies from manim-gallery, you already have the tool installed. No need to checkout the manim or the manim-gallery source.

> I see that your workflow is super useful, when it comes to complex projects, buuuut it might be a little overkill for this kind of project, where the main idea is to add single files.
> There is a "Propose new file" option, when I am in my browser in the original repo.

If I remember correctly, this button will also create a fork with a pull request. Go ahead trying it out. Also, maybe you don't need a local copy at all. As long as your file is being rendered by manim (with the version manim-gallery uses), you can go along using the online editor of GitHub.

**Comment by kolibril13** [comment]
ok, you can see it
